### ISSUE TITLE
Write simple tests

### ISSUE THREAD

**Issue by saru95** [saru95/ideone-npm#1]
This project needs simple tests using ava or tape or any other testing framework to test the underlying api it uses .

**Comment by ykt** [comment]
Hi @saru95 
Do you expect on test unit level or integration test Against to `Ideone` with assert the expected output of the API?

**Comment by saru95** [comment]
Assert the expected output . As I said, needs to be simple .

**Comment by KayvanMazaheri** [comment]
@saru95 I'm working on it.

**Comment by ykt** [comment]
@saru95 please check out the [PR](https://github.com/saru95/ideone-npm/pull/2), I believe that would dead simple test using `ava`.
